CREATE TABLE hr
(
    id         SERIAL PRIMARY KEY,
    user_id    INTEGER NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    company_id INTEGER NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    dep_id     INTEGER NOT NULL REFERENCES departments (id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE vacancies ADD COLUMN company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE;