server:
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "jumyste-app-db"
  sslmode: "disable"

jwt:
  secret: "secretkey"
  expiration_hours: 1

smtp:
  host: "localhost"
  port: "1025"
  username: ""
  password: ""
  sender: "noreply@jumyste-app.local"  # Исправлено
